apiVersion: kubeagents.x-k8s.io/v1alpha1
kind: DevTeamAgent
metadata:
  name: devteam-agent-autopilot-cluster-1-us-central1-devteam-app-ns
  namespace: kubeagents-system
spec:
  harness:
    projectId: "kube-agents-gke"
    clusterName: "autopilot-cluster-1"
    location: "us-central1"
    namespace: "devteam-app-ns"
  integration:
    github:
      gitRepo: "git@github.com:gke-labs/kube-agents-mock-payments.git"
    hermes:
      apiServerSecretRef:
        name: "platform-agent-secrets"
        key: "API_SERVER_KEY"
  deployment:
    image: "us-central1-docker.pkg.dev/kube-agents-gke/kubeagents-operator-repo/devteam-agent"
    tag: "latest"
  security:
    serviceAccountName: "kubeagents-devteam-agent"
    serviceAccountAnnotations:
      iam.gke.io/gcp-service-account: "kubeagents-devteam-gsa@kube-agents-gke.iam.gserviceaccount.com"
