apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-agent-<CLUSTER_NAME>-<CLUSTER_LOCATION>-cluster-admin
  labels:
    app: operator-agent-<CLUSTER_NAME>-<CLUSTER_LOCATION>
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: <GSA_EMAIL>
  - kind: ServiceAccount
    name: operator-agent-<CLUSTER_NAME>-<CLUSTER_LOCATION>-sa
    namespace: agent-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
