resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: us-east4-docker.pkg.dev/dharb-gkedemos/kube-agents/kubeagents-controller
  newTag: separate-container
