apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: agent-system
spec:
  selector:
    app: gemma-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
