apiVersion: v1
kind: Service
metadata:
  name: platform-agent
  namespace: kubeagents-system
  labels:
    app.kubernetes.io/name: platform-agent
    app.kubernetes.io/instance: kubeagents-system-platform-agent
    app.kubernetes.io/part-of: kube-agents
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app: platform-agent
  ports:
    - name: api
      protocol: TCP
      port: 8642
      targetPort: 8642
    - name: dashboard
      protocol: TCP
      port: 9119
      targetPort: 9119
  type: ClusterIP
