#!/usr/bin/env python3
"""Generates or checks charts/kube-agents/files/footprint.yaml from an operator golden (#749).

The chart's quota preflight cannot render the operator's pods, so it needs their resource
totals as data. This sums them from the operator's golden manifest for the default example
CR and writes them to a file the chart reads with `.Files.Get`.

The source is a golden, not a live render and not k8s-operator/config/, so changing the
operator's resources takes two steps in order: re-bless the golden
(cd k8s-operator && go test ./internal/testing/... -update), then `make chart-sync`.
Syncing first regenerates the old numbers from the stale golden. The golden is written by
k8s-operator/internal/testing/golden_test.go, so ./internal/testing/... is the package to
run: ./internal/controller/... defines an unrelated -update flag of its own, which makes
the wrong command pass while leaving this golden stale.

Verified in CI by `make chart-check`, which runs this with --check.

Exit codes: 0 in sync, _EXIT_DRIFT on a difference, _EXIT_CANNOT_RUN when the generator
could not run (no PyYAML, an unreadable golden, a golden it cannot account for).
"""

import argparse
import difflib
import math
import pathlib
import sys

# `make chart-check` distinguishes these: 1 means the committed file has drifted and the
# fix is to re-sync, anything else means the check could not run and the fix is different.
# Declared above the PyYAML import because a missing dependency has to exit with the
# second of them: an unhandled ImportError exits 1 and is read as drift.
_EXIT_DRIFT = 1
_EXIT_CANNOT_RUN = 2
_UTF8 = "utf-8"

_MISSING_PYYAML = (
    "generate_chart_footprint needs PyYAML: python3 -m pip install pyyaml"
    " (or make test-python-deps)"
)

try:
    import yaml
except ImportError:
    print(_MISSING_PYYAML, file=sys.stderr)
    sys.exit(_EXIT_CANNOT_RUN)

_ROOT = pathlib.Path(__file__).resolve().parents[1]
_GOLDEN_MANIFEST = (
    _ROOT
    / "k8s-operator"
    / "internal"
    / "testing"
    / "testdata"
    / "platform"
    / "expected"
    / "platformagent.yaml"
)
_FOOTPRINT_FILE = _ROOT / "charts" / "kube-agents" / "files" / "footprint.yaml"

_HEADER = (
    "# GENERATED by `make chart-sync` — do not edit.\n"
    "# Summed from the operator's golden manifest for the default example CR\n"
    "# (k8s-operator/internal/testing/testdata/platform/expected/platformagent.yaml),\n"
    "# not from a live render. Re-bless that golden before syncing, or this regenerates\n"
    "# the old numbers. See hack/sync-chart-manifests.sh.\n"
)

# Workload and container names in the golden. The generator finds these by name, so a
# rename in the operator surfaces here as a "not found in the golden" error rather than
# as a silently-zero footprint.
_SHELL_WORKLOAD = "platformagent-shell"
_SHELL_CONTAINER = "shell"
_CRED_PROXY_WORKLOAD = "platformagent-credential-proxy"
_CRED_PROXY_CONTAINER = "envoy-credential-proxy"
_GATEWAY_WORKLOAD = "platformagent-gateway"
_AGENT_CONTAINER = "platform-agent"
_DASHBOARD_CONTAINER = "platform-agent-dashboard"
_FLUENT_BIT_CONTAINER = "fluent-bit"
_AGENT_API_AUTH_CONTAINER = "agent-api-auth"
_SANDBOX_CLEANUP_CONTAINER = "sandbox-credential-cleanup"
_SANDBOX_SSH_KEY_CONTAINER = "sandbox-ssh-key"

_KIND_STATEFULSET = "StatefulSet"
_KIND_DEPLOYMENT = "Deployment"
_KIND_PVC = "PersistentVolumeClaim"
_KIND_DAEMONSET = "DaemonSet"
_KIND_REPLICASET = "ReplicaSet"
_KIND_REPLICATION_CONTROLLER = "ReplicationController"
_KIND_JOB = "Job"
_KIND_CRON_JOB = "CronJob"
_KIND_POD = "Pod"

# Kinds that put pods on a cluster. Every golden document of one of these has to reach the
# footprint or be ignored on purpose; _check_completeness is what enforces that.
_POD_BEARING_KINDS = frozenset(
    {
        _KIND_DEPLOYMENT,
        _KIND_STATEFULSET,
        _KIND_DAEMONSET,
        _KIND_REPLICASET,
        _KIND_REPLICATION_CONTROLLER,
        _KIND_JOB,
        _KIND_CRON_JOB,
        _KIND_POD,
    }
)

_KIND_FIELD = "kind"
_METADATA_FIELD = "metadata"
_SPEC_FIELD = "spec"
_TEMPLATE_FIELD = "template"
_JOB_TEMPLATE_FIELD = "jobTemplate"
_CONTAINERS_FIELD = "containers"
_INIT_CONTAINERS_FIELD = "initContainers"
_NAME_FIELD = "name"
_RESOURCES_FIELD = "resources"
_RESTART_POLICY_FIELD = "restartPolicy"
_VOLUME_CLAIM_TEMPLATES_FIELD = "volumeClaimTemplates"

# On an init container this makes it a native sidecar: it runs for the life of the pod and
# is added to the pod's request rather than only being the floor under it.
_RESTART_POLICY_ALWAYS = "Always"

_DIFF_COMMITTED_LABEL = "committed footprint.yaml"
_DIFF_GENERATED_LABEL = "regenerated from the operator golden"

_REQUESTS = "requests"
_LIMITS = "limits"
_CPU = "cpu"
_MEMORY = "memory"
_EPHEMERAL_STORAGE = "ephemeral-storage"
_STORAGE = "storage"

_MIB = 1024**2
_GIB = 1024**3
_MILLICORES_PER_CORE = 1000
_MILLI_DIVISOR = 1000
_ZERO_QUANTITY = "0"

_REPLICAS_FIELD = "replicas"

_OPERATOR_RENDERED = "operatorRendered"
_AGENT_POD = "agentPod"
_BASE = "base"
_DASHBOARD = "dashboard"
_SHELL_SANDBOX = "shellSandbox"
_CREDENTIAL_PROXY = "credentialProxy"
_STORAGE_SECTION = "storage"
_PERSISTENT_VOLUME_CLAIMS = "persistentVolumeClaims"
_STORAGE_REQUEST = "storageRequest"
_STORAGE_BYTES_REQUEST = "storageBytesRequest"
_CPU_MILLIS_REQUEST = "cpuMillisRequest"
_CPU_MILLIS_LIMIT = "cpuMillisLimit"
_MEMORY_BYTES_REQUEST = "memoryBytesRequest"
_MEMORY_BYTES_LIMIT = "memoryBytesLimit"
_EPHEMERAL_STORAGE_BYTES_REQUEST = "ephemeralStorageBytesRequest"
_EPHEMERAL_STORAGE_BYTES_LIMIT = "ephemeralStorageBytesLimit"
_PODS = "pods"

_KEY_SEPARATOR = "/"


def _workload_key(kind: str, name: str) -> str:
    """Identify a workload the way the guard's messages and ignore lists name it."""
    return f"{kind}{_KEY_SEPARATOR}{name}"


def _container_key(workload_key: str, container: str) -> str:
    return f"{workload_key}{_KEY_SEPARATOR}{container}"


_SHELL_WORKLOAD_KEY = _workload_key(_KIND_STATEFULSET, _SHELL_WORKLOAD)
_CRED_PROXY_WORKLOAD_KEY = _workload_key(_KIND_DEPLOYMENT, _CRED_PROXY_WORKLOAD)
_GATEWAY_WORKLOAD_KEY = _workload_key(_KIND_DEPLOYMENT, _GATEWAY_WORKLOAD)

# Pod-bearing workloads the footprint deliberately leaves out, and why. Empty today: the
# operator renders three, and all three are summed. An entry here excludes the workload
# and everything in it, so it needs a reason the release does not pay for those pods.
_IGNORED_WORKLOADS: dict[str, str] = {}

# Containers inside the summed workloads that deliberately do not change the totals, and
# why. A pod's effective request is max(largest init container, sum of the regular and
# sidecar containers), so an ordinary init container only counts when it is larger than
# that sum -- which is the thing to recheck before adding an entry here. _check_completeness
# rechecks only that the container is still an ordinary init container; that it is still
# the smaller of the two is on whoever changes its resources.
_IGNORED_CONTAINERS: dict[str, str] = {
    _container_key(_GATEWAY_WORKLOAD_KEY, _SANDBOX_CLEANUP_CONTAINER): (
        "ordinary init container, requests less than the gateway pod's container sum"
    ),
    _container_key(_GATEWAY_WORKLOAD_KEY, _SANDBOX_SSH_KEY_CONTAINER): (
        "ordinary init container, requests less than the gateway pod's container sum"
    ),
}

_COMPLETENESS_ADVICE = (
    "Each one is either part of what an install costs or it is not. Sum it into "
    "extract_footprint as a top-level key under operatorRendered (where the chart's "
    "kube-agents.quotaRequirements template generically iterates and counts it), or add "
    "it to _IGNORED_WORKLOADS or _IGNORED_CONTAINERS in this file with the reason it does "
    "not change the totals. Then run `make chart-sync`."
)

_YAML_STR_TAG = "tag:yaml.org,2002:str"
_DOUBLE_QUOTE = '"'


class _PrettierCompatibleDumper(yaml.SafeDumper):
    """Writes the quote style Prettier normalises to.

    The generated file is a `.yaml` under `charts/`, so the Prettier Check workflow
    formats it like any other. PyYAML single-quotes a string that would otherwise parse
    as something else -- a CPU limit of `1`, an `ephemeral-storage` of `0` -- and Prettier
    rewrites those to double quotes. Emitting single quotes therefore produces a file that
    fails `prettier --check` on the first push, and reformatting the file by hand makes
    `--check` here report drift instead. Emitting what Prettier wants keeps both green.
    """


def _represent_str(dumper, data):
    """Double-quote only what has to be quoted, matching Prettier rather than quoting all."""
    resolved = dumper.resolve(yaml.ScalarNode, data, (True, False))
    style = None if resolved == _YAML_STR_TAG else _DOUBLE_QUOTE
    return dumper.represent_scalar(_YAML_STR_TAG, data, style=style)


_PrettierCompatibleDumper.add_representer(str, _represent_str)

_BINARY_SI_UNITS = {
    "Ki": 1024,
    "Mi": _MIB,
    "Gi": _GIB,
    "Ti": 1024**4,
    "Pi": 1024**5,
    "Ei": 1024**6,
}

_DECIMAL_SI_UNITS = {
    "k": 1000,
    "M": 1000**2,
    "G": 1000**3,
    "T": 1000**4,
    "P": 1000**5,
    "E": 1000**6,
}


def parse_bytes(val: str | int | float) -> int:
    """Parse a Kubernetes memory/storage quantity to integer bytes.

    Reads every form kube-agents.parseBytes reads, including the fractional and exponent
    spellings its regex allows (`1.5Gi`, `1e3`). The two run over the same quantities --
    this generator over the operator golden, the template over the values and the quota it
    writes -- so a form one accepts and the other rejects means `make chart-check` crashes
    on a manifest the chart itself would have rendered.
    """
    if isinstance(val, (int, float)):
        return int(val)
    val = str(val).strip()
    if not val:
        return 0
    if val.endswith("m"):
        return math.ceil(float(val[:-1]) / _MILLI_DIVISOR)
    for unit, mult in _BINARY_SI_UNITS.items():
        if val.endswith(unit):
            return int(float(val[: -len(unit)]) * mult)
    for unit, mult in _DECIMAL_SI_UNITS.items():
        if val.endswith(unit):
            return int(float(val[: -len(unit)]) * mult)
    return int(float(val))


def parse_cpu_millis(val: str | int | float) -> int:
    """Parse a Kubernetes CPU quantity to integer millicores.

    Same contract as parse_bytes: every form kube-agents.parseCpuMillis reads, fractional
    millicores (`500.5m`) among them.
    """
    if isinstance(val, (int, float)):
        return int(float(val) * _MILLICORES_PER_CORE)
    val = str(val).strip()
    if not val:
        return 0
    if val.endswith("m"):
        return int(float(val[:-1]))
    for unit, mult in _DECIMAL_SI_UNITS.items():
        if val.endswith(unit):
            return int(float(val[: -len(unit)]) * mult * _MILLICORES_PER_CORE)
    return int(float(val) * _MILLICORES_PER_CORE)


def format_cpu(millis: int) -> str:
    """Render millicores the way kube-agents.formatCpu does, so the two agree."""
    if millis and millis % _MILLICORES_PER_CORE == 0:
        return str(millis // _MILLICORES_PER_CORE)
    return f"{millis}m"


def format_bytes(num_bytes: int) -> str:
    """Render bytes the way kube-agents.formatBytes does, so the two agree."""
    if num_bytes and num_bytes % _GIB == 0:
        return f"{num_bytes // _GIB}Gi"
    if num_bytes and num_bytes % _MIB == 0:
        return f"{num_bytes // _MIB}Mi"
    return str(num_bytes)


def _declared(val) -> bool:
    """Whether a container declared this quantity at all.

    `if not val` would call a declared `0` absent and fall through to the limit, the same
    trap kube-agents.declaredQuantity avoids on the chart side. A golden written by
    resource.Quantity spells zero as the string `"0"`, which is truthy, so this only bites
    on a hand-edited manifest -- but the two sides have to agree on what "omitted" means.
    """
    return val is not None and str(val).strip() != ""


def _quantity(container: dict, section: str, key: str, parse) -> int:
    resources = container.get(_RESOURCES_FIELD) or {}
    val = (resources.get(section) or {}).get(key)
    if not _declared(val):
        val = _ZERO_QUANTITY
        if section == _REQUESTS:
            # When requests are omitted, Kubernetes defaults the request to match the limit.
            limit = (resources.get(_LIMITS) or {}).get(key)
            if _declared(limit):
                val = limit
    return parse(val)


def _sum_quantity(containers: list, section: str, key: str, parse) -> int:
    return sum(_quantity(c, section, key, parse) for c in containers)


def _workload_entry(containers: list, pods: int = 1, replicas: int = 1) -> dict:
    """Sum a set of co-scheduled containers into one footprint entry.

    Callers pass the regular and native sidecar init containers that contribute to the pod's
    resources; ordinary init containers that run to completion and request less than the
    container sum are excluded before calling.

    When `replicas` is greater than 1 (as read from `spec.replicas`), total pods and resource
    quantities are scaled by `replicas`.
    """
    total_pods = pods * replicas
    req_cpu = _sum_quantity(containers, _REQUESTS, _CPU, parse_cpu_millis) * replicas
    lim_cpu = _sum_quantity(containers, _LIMITS, _CPU, parse_cpu_millis) * replicas
    req_mem = _sum_quantity(containers, _REQUESTS, _MEMORY, parse_bytes) * replicas
    lim_mem = _sum_quantity(containers, _LIMITS, _MEMORY, parse_bytes) * replicas
    req_eph = _sum_quantity(containers, _REQUESTS, _EPHEMERAL_STORAGE, parse_bytes) * replicas
    lim_eph = _sum_quantity(containers, _LIMITS, _EPHEMERAL_STORAGE, parse_bytes) * replicas

    return {
        _REQUESTS: {
            _CPU: format_cpu(req_cpu),
            _MEMORY: format_bytes(req_mem),
            _EPHEMERAL_STORAGE: format_bytes(req_eph),
        },
        _LIMITS: {
            _CPU: format_cpu(lim_cpu),
            _MEMORY: format_bytes(lim_mem),
            _EPHEMERAL_STORAGE: format_bytes(lim_eph),
        },
        _CPU_MILLIS_REQUEST: req_cpu,
        _CPU_MILLIS_LIMIT: lim_cpu,
        _MEMORY_BYTES_REQUEST: req_mem,
        _MEMORY_BYTES_LIMIT: lim_mem,
        _EPHEMERAL_STORAGE_BYTES_REQUEST: req_eph,
        _EPHEMERAL_STORAGE_BYTES_LIMIT: lim_eph,
        _PODS: total_pods,
    }


def _replicas(doc: dict) -> int:
    """Read spec.replicas from a workload document, defaulting to 1."""
    replicas = (doc.get(_SPEC_FIELD) or {}).get(_REPLICAS_FIELD)
    return 1 if replicas is None else int(replicas)


def _pod_spec(doc: dict) -> dict:
    kind = doc.get(_KIND_FIELD)
    spec = doc.get(_SPEC_FIELD) or {}
    if kind == _KIND_POD:
        return spec
    if kind == _KIND_CRON_JOB:
        job_template = spec.get(_JOB_TEMPLATE_FIELD) or {}
        job_spec = job_template.get(_SPEC_FIELD) or {}
        pod_template = job_spec.get(_TEMPLATE_FIELD) or {}
        return pod_template.get(_SPEC_FIELD) or {}
    return (spec.get(_TEMPLATE_FIELD) or {}).get(_SPEC_FIELD) or {}


def _claim_storage(claim: dict) -> int:
    resources = (claim.get(_SPEC_FIELD) or {}).get(_RESOURCES_FIELD) or {}
    return parse_bytes((resources.get(_REQUESTS) or {}).get(_STORAGE, _ZERO_QUANTITY))


def _pod_containers(spec: dict) -> list:
    """Every container in a pod spec, regular and init alike, in declaration order."""
    return list(spec.get(_CONTAINERS_FIELD) or []) + list(
        spec.get(_INIT_CONTAINERS_FIELD) or []
    )


def _describe_container(container: dict) -> str:
    """Name a container and what it asks for, so a guard failure shows its size."""
    name = container.get(_NAME_FIELD)
    cpu = _quantity(container, _REQUESTS, _CPU, parse_cpu_millis)
    memory = _quantity(container, _REQUESTS, _MEMORY, parse_bytes)
    return f"{name!r} (requests {format_cpu(cpu)} cpu, {format_bytes(memory)} memory)"


def _check_completeness(pod_workloads: dict, summed_containers: set) -> None:
    """Fail on anything in the golden that the footprint neither sums nor ignores.

    The generator finds what it sums by name, which makes a rename loud and an addition
    silent: a workload or container the operator started rendering would be missing from
    footprint.yaml, and `make chart-check` would report no drift because nothing looked
    for it. An undercounted footprint is worse than none, because the quota preflight
    passes the install it exists to stop. This is what looks.
    """
    unaccounted = []
    for workload_key, spec in sorted(pod_workloads.items()):
        if workload_key in _IGNORED_WORKLOADS:
            continue
        containers = _pod_containers(spec)
        summed_here = [
            container
            for container in containers
            if _container_key(workload_key, container.get(_NAME_FIELD))
            in summed_containers
        ]
        if not summed_here:
            unaccounted.append(
                f"workload {workload_key} contributes nothing to the footprint"
            )
            continue
        for container in containers:
            key = _container_key(workload_key, container.get(_NAME_FIELD))
            if key in summed_containers:
                continue
            if key in _IGNORED_CONTAINERS:
                # Every reason in _IGNORED_CONTAINERS rests on the container being an
                # ordinary init container, which a pod's request only pays for while it
                # runs. restartPolicy: Always makes it a native sidecar that is added to
                # the sum instead, so the reason no longer holds and the ignore lapses.
                if container.get(_RESTART_POLICY_FIELD) == _RESTART_POLICY_ALWAYS:
                    unaccounted.append(
                        f"container {_describe_container(container)} in {workload_key}"
                        " is ignored as an init container but now restarts Always,"
                        " which counts it toward the pod's request"
                    )
                continue
            unaccounted.append(
                f"container {_describe_container(container)} in {workload_key}"
                " is neither summed nor ignored"
            )
    if unaccounted:
        found = "\n".join(f"  - {item}" for item in unaccounted)
        raise ValueError(
            f"the golden renders pods the footprint does not account for:\n{found}\n"
            f"{_COMPLETENESS_ADVICE}"
        )


def extract_footprint() -> dict:
    """Extract operator-rendered resource requirements from the golden manifest."""
    if not _GOLDEN_MANIFEST.is_file():
        raise FileNotFoundError(f"Golden manifest missing: {_GOLDEN_MANIFEST}")

    docs = list(yaml.safe_load_all(_GOLDEN_MANIFEST.read_text()))

    shell_containers = {}
    cred_proxy_containers = {}
    gateway_containers = {}
    gateway_init_containers = {}
    shell_replicas = 1
    cred_proxy_replicas = 1
    gateway_replicas = 1
    # Every pod-bearing document, summed or not, for _check_completeness below.
    pod_workloads = {}
    pvc_count = 0
    storage_bytes = 0

    for doc in docs:
        if not doc or not isinstance(doc, dict):
            continue
        kind = doc.get(_KIND_FIELD)
        name = (doc.get(_METADATA_FIELD) or {}).get(_NAME_FIELD)
        workload_key = _workload_key(kind, name)
        if workload_key in _IGNORED_WORKLOADS:
            continue
        spec = _pod_spec(doc)

        if kind == _KIND_PVC:
            # Standalone claims: one object each, and they do not scale with replicas.
            pvc_count += 1
            storage_bytes += _claim_storage(doc)
            continue

        if kind in _POD_BEARING_KINDS:
            pod_workloads[workload_key] = spec

        if kind == _KIND_STATEFULSET and name == _SHELL_WORKLOAD:
            shell_containers = {
                c.get(_NAME_FIELD): c for c in spec.get(_CONTAINERS_FIELD, [])
            }
            shell_replicas = _replicas(doc)
        elif kind == _KIND_DEPLOYMENT and name == _CRED_PROXY_WORKLOAD:
            cred_proxy_containers = {
                c.get(_NAME_FIELD): c for c in spec.get(_CONTAINERS_FIELD, [])
            }
            cred_proxy_replicas = _replicas(doc)
        elif kind == _KIND_DEPLOYMENT and name == _GATEWAY_WORKLOAD:
            gateway_containers = {
                c.get(_NAME_FIELD): c for c in spec.get(_CONTAINERS_FIELD, [])
            }
            gateway_init_containers = {
                c.get(_NAME_FIELD): c for c in spec.get(_INIT_CONTAINERS_FIELD, [])
            }
            gateway_replicas = _replicas(doc)

        if kind == _KIND_STATEFULSET:
            # A StatefulSet's volumeClaimTemplates become one claim per replica.
            replicas = _replicas(doc)
            for claim in (doc.get(_SPEC_FIELD) or {}).get(_VOLUME_CLAIM_TEMPLATES_FIELD) or []:
                pvc_count += replicas
                storage_bytes += _claim_storage(claim) * replicas

    required = [
        (shell_containers, _SHELL_CONTAINER, _SHELL_WORKLOAD),
        (cred_proxy_containers, _CRED_PROXY_CONTAINER, _CRED_PROXY_WORKLOAD),
        (gateway_containers, _AGENT_CONTAINER, _GATEWAY_WORKLOAD),
        (gateway_containers, _DASHBOARD_CONTAINER, _GATEWAY_WORKLOAD),
        (gateway_containers, _FLUENT_BIT_CONTAINER, _GATEWAY_WORKLOAD),
        (gateway_init_containers, _AGENT_API_AUTH_CONTAINER, _GATEWAY_WORKLOAD),
    ]
    for containers, container_name, workload in required:
        if container_name not in containers:
            raise ValueError(
                f"container {container_name!r} not found in {workload} in the golden"
            )

    if gateway_replicas != 1:
        raise ValueError(
            f"{_GATEWAY_WORKLOAD} spec.replicas is {gateway_replicas}, expected 1. "
            "The footprint records one gateway replica's base for the chart to scale "
            "via availability.replicas."
        )

    # The containers the entries below sum, named the way the guard names them. Dropping
    # one from an entry without dropping it here leaves it unaccounted and the guard says
    # so; the reverse -- listed here but summed nowhere -- is the hole the guard cannot
    # see, so the two move together.
    summed_containers = {
        _container_key(_SHELL_WORKLOAD_KEY, _SHELL_CONTAINER),
        _container_key(_CRED_PROXY_WORKLOAD_KEY, _CRED_PROXY_CONTAINER),
        _container_key(_GATEWAY_WORKLOAD_KEY, _AGENT_CONTAINER),
        _container_key(_GATEWAY_WORKLOAD_KEY, _DASHBOARD_CONTAINER),
        _container_key(_GATEWAY_WORKLOAD_KEY, _FLUENT_BIT_CONTAINER),
        _container_key(_GATEWAY_WORKLOAD_KEY, _AGENT_API_AUTH_CONTAINER),
    }
    _check_completeness(pod_workloads, summed_containers)

    # The agent pod's base is everything always present: the agent, its log shipper, and the
    # agent-api-auth native sidecar (declared as an init container with restartPolicy:
    # Always, so it counts toward the pod's request like a regular container).
    agent_pod_base = [
        gateway_containers[_AGENT_CONTAINER],
        gateway_containers[_FLUENT_BIT_CONTAINER],
        gateway_init_containers[_AGENT_API_AUTH_CONTAINER],
    ]

    return {
        _OPERATOR_RENDERED: {
            _AGENT_POD: {
                # One pod for the base. The dashboard is another container in that same pod,
                # so it adds resources but no pod.
                _BASE: _workload_entry(agent_pod_base, pods=1),
                _DASHBOARD: _workload_entry(
                    [gateway_containers[_DASHBOARD_CONTAINER]], pods=0
                ),
            },
            _SHELL_SANDBOX: _workload_entry(
                [shell_containers[_SHELL_CONTAINER]], pods=1, replicas=shell_replicas
            ),
            _CREDENTIAL_PROXY: _workload_entry(
                [cred_proxy_containers[_CRED_PROXY_CONTAINER]],
                pods=1,
                replicas=cred_proxy_replicas,
            ),
            # Claims are release-scoped rather than per-agent-replica: scaling the agent does
            # not create more of them, so the preflight must not multiply these.
            _STORAGE_SECTION: {
                _PERSISTENT_VOLUME_CLAIMS: pvc_count,
                _STORAGE_REQUEST: format_bytes(storage_bytes),
                _STORAGE_BYTES_REQUEST: storage_bytes,
            },
        }
    }


def _drift_diff(committed: str, generated: str) -> str:
    """A unified diff of the two, so --check shows what moved rather than only that it did."""
    return "\n".join(
        difflib.unified_diff(
            committed.splitlines(),
            generated.splitlines(),
            _DIFF_COMMITTED_LABEL,
            _DIFF_GENERATED_LABEL,
            lineterm="",
        )
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check for drift without writing")
    args = parser.parse_args()

    try:
        data = extract_footprint()
    except (OSError, ValueError, KeyError, TypeError, yaml.YAMLError) as err:
        # Not drift: the check could not be performed at all, and the fix is a different
        # one. OSError covers the golden being absent and being unreadable alike; both
        # leave the generator with nothing to compare, and neither is fixed by re-syncing.
        print(f"ERROR: cannot build the chart footprint: {err}", file=sys.stderr)
        sys.exit(_EXIT_CANNOT_RUN)

    content = _HEADER + yaml.dump(data, Dumper=_PrettierCompatibleDumper, sort_keys=False)

    if args.check:
        if not _FOOTPRINT_FILE.is_file():
            print(
                f"ERROR: {_FOOTPRINT_FILE} does not exist (run 'make chart-sync')",
                file=sys.stderr,
            )
            sys.exit(_EXIT_DRIFT)
        try:
            committed = _FOOTPRINT_FILE.read_text(encoding=_UTF8)
        except OSError as err:
            print(f"ERROR: cannot read {_FOOTPRINT_FILE}: {err}", file=sys.stderr)
            sys.exit(_EXIT_CANNOT_RUN)
        if committed != content:
            print(_drift_diff(committed, content), file=sys.stderr)
            print(
                f"ERROR: {_FOOTPRINT_FILE} is out of date vs {_GOLDEN_MANIFEST}",
                file=sys.stderr,
            )
            sys.exit(_EXIT_DRIFT)
        print("Chart footprint is in sync with the operator golden.")
    else:
        try:
            _FOOTPRINT_FILE.write_text(content, encoding=_UTF8)
        except OSError as err:
            print(f"ERROR: cannot write {_FOOTPRINT_FILE}: {err}", file=sys.stderr)
            sys.exit(_EXIT_CANNOT_RUN)
        print(f"Generated {_FOOTPRINT_FILE} from {_GOLDEN_MANIFEST}")


if __name__ == "__main__":
    main()
